package org.cerner.patientportal.dao;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.cerner.patientportal.bean.Patient;
import org.cerner.patientportal.dao.PatientDAO;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;

import util.DataBaseConnection;

public class PatientDAOTest {

	List<Patient> list = new ArrayList<Patient>();

	@Mock
	Patient entity;
	DataBaseConnection connection;
	Connection con;
	PatientDAO dao;
	PreparedStatement stmt;

	@Before
	public void create() throws Exception {
		entity = new Patient();
		dao = mock(PatientDAO.class);
		connection = mock(DataBaseConnection.class);
	}

	@Test
	public void testPatientData() throws Exception {
		entity.setFirstName("Ashok");
		entity.setLastName("Kumar");
		entity.setDateOfBirth("12-21-2012");
		entity.setGender("Male");
		entity.setPhoneNo("9949850519");
		entity.setEmailId("ashok@cerner.com");
		when(dao.registerPatient(entity)).thenReturn(null);
		assertEquals(dao.registerPatient(entity), null);
	}

	/**
	 * @throws SqlException
	 *             since we are providing the lastName as null
	 */
	@Test(expected = SQLException.class)
	public void testPatientDataByNull() throws Exception {
		entity.setFirstName("Ashok");
		entity.setLastName(null);
		entity.setDateOfBirth("12-21-2012");
		entity.setGender("Male");
		entity.setPhoneNo("9949850519");
		entity.setEmailId("ashok@cerner.com");
		doThrow(new SQLException()).when(dao).registerPatient(entity);
	}

	/**
	 * @throws SqlException
	 *             since we are providing the firstName as null
	 */
	@Test(expected = SQLException.class)
	public void testPatientDataByFirstName() throws Exception {
		entity.setFirstName(null);
		entity.setLastName("Kumar");
		entity.setDateOfBirth("12-21-2012");
		entity.setGender("Male");
		entity.setPhoneNo("9949850519");
		entity.setEmailId("ashok@cerner.com");
		doThrow(new SQLException()).when(dao).registerPatient(entity);
	}

	/**
	 * @This is test for fetching the patientId which has been generated by
	 *       "registerPatient" method.
	 */
	@Test
	public void testFetchPatientId() throws Exception {
		when(dao.fetchPatientId()).thenReturn(8);
		assertEquals(dao.fetchPatientId(), 8);
	}

	/**
	 * @This is test for fetching the patientId which has been generated by
	 *       "registerPatient" method and we are asserted to value from that method
	 *       only.So it will pass
	 */
	@Test
	public void testFetchPatientIdByNull() throws Exception {
		when(dao.fetchPatientId()).thenReturn(8);
		assertEquals(dao.fetchPatientId(), 8);
	}

	@Test
	public void testGetPatientList() throws Exception {
		entity.setPatientId(0);
		entity.setFirstName("123");
		entity.setLastName("kumar");
		entity.setDateOfBirth("01-01-2000");
		when(dao.getPatientList(entity)).thenReturn(null);
		assertEquals(dao.getPatientList(entity), null);
	}

	@Test
	public void testGetPatientListByPatientId() throws Exception {
		entity.setPatientId(9);
		when(dao.getPatientList(entity)).thenReturn(list);
		assertEquals(dao.getPatientList(entity), list);
	}

	@Test
	public void testGetPatientListByFirstName() throws Exception {
		entity.setFirstName("abc");
		when(dao.getPatientList(entity)).thenReturn(list);
		assertEquals(dao.getPatientList(entity), list);
	}

	@Test
	public void testGetPatientListByLastName() throws Exception {
		entity.setLastName("kumar");
		when(dao.getPatientList(entity)).thenReturn(list);
		assertEquals(dao.getPatientList(entity), list);
	}

	@Test
	public void testGetPatientListByDateOfBirth() throws Exception {
		entity.setDateOfBirth("2018-03-06");
		when(dao.getPatientList(entity)).thenReturn(list);
		assertEquals(dao.getPatientList(entity), list);
	}

	@Test
	public void testGetPatientListByAllData() throws Exception {

		entity.setPatientId(90);
		entity.setFirstName("abc");
		entity.setLastName("xyz");
		entity.setDateOfBirth("2018-03-06");
		when(dao.getPatientList(entity)).thenReturn(list);
		assertEquals(0, dao.getPatientList(entity).size());
	}
}
