#URL to connect to the particular server
registerUrl = http://localhost:8069/patientPortalSystem/webapi/patients/register
searchUrl = http://localhost:8069/patientPortalSystem/webapi/patients/search?
